---
title: "IODS course project"
author: "Faranak Halali"
---

***
  
```{r child = "chapter1.Rmd"}
```
  
***
  
```{r child = "chapter2.Rmd"}
```

***
Read data
```{r}
library(dplyr)
Faran <- read.table("http://www.helsinki.fi/~kvehkala/JYTmooc/JYTOPKYS3-data.txt", sep="\t", header=TRUE)
```
Exploring data

```{r}
str(Faran)
dim(Faran)
```
Deep, surf, stra questions
```{r}
deep_questions <- c("D03", "D11", "D19", "D27", "D07", "D14", "D22", "D30","D06",  "D15", "D23", "D31")
surface_questions <- c("SU02","SU10","SU18","SU26", "SU05","SU13","SU21","SU29","SU08","SU16","SU24","SU32")
strategic_questions <- c("ST01","ST09","ST17","ST25","ST04","ST12","ST20","ST28")
deep_columns <- select(Faran,one_of(deep_questions))
surf_columns <- select(Faran, one_of(surface_questions))
stra_columns <- select(Faran, one_of(strategic_questions))
```
Keeping selected data
```{r}
Faran$deep <- rowMeans(deep_columns)
Faran$surf <- rowMeans(surf_columns)
Faran$stra <- rowMeans(stra_columns)
keep <- c("Age", "gender", "Attitude", "Points", "deep", "surf", "stra")
Newdata <- select(Faran, one_of(keep))
```
Scaling
```{r}
deep_scaled <- Faran$deep/12
surf_scaled <- Faran$surf/12
stra_sclaed <- Faran$stra/8
Newdata <- filter(Newdata, Points > 0)
```
Reading data
```{r}
write.csv(Newdata, file = "Newdata.csv")
```
Exploring data
```{r}
dim(Newdata)
str(Newdata)
```
Plot matrix
```{r}
pairs(Newdata)
```

Regression model and its summary
```{r}
my_regressionmodel <- lm(Points ~ Attitude + stra + deep, data = Newdata)
summary(my_regressionmodel)
```

Regression model 2 excluding nonsignificant explanators
```{r}
my_regressionmodel2 <- lm(Points ~ Attitude, data = Newdata)
summary(my_regressionmodel2)
```

Summary of variables
```{r}
summary(Newdata$deep)
summary(Newdata$surf)
summary(Newdata$stra)
summary(Newdata$Age)
summary(Newdata$gender)
summary(Newdata$Attitude)
summary(Newdata$Points)
```

Regression diagnostic plots
```{r}
plot(my_regressionmodel2, which = c(1,2,5))
```

***
```{r child = "chapter3.Rmd"}
```


 
 


